# for Docker Compose
FROM node:18-slim
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
RUN apt-get update && \
  apt-get install -y --no-install-recommends libsqlite3-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm ci && mv ./node_modules /

CMD ["/bin/bash", "run_dev.sh"]
