version: '3'
volumes:
  node_modules:
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.local
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./node_modules
        target: /app/node_modules
    env_file:
      - '.env'
